export enum HTML_NODES {
  START_BTN = 'STRESS_START_BTN',
  STOP_BTN = 'STRESS_STOP_BTN',
  STATUS_TEXT = 'STRESS_STATUS_TEXT',
  CB_TICK_RENDER = 'CB_TICK_RENDER',
  CB_REQUEST_TEST = 'CB_REQUEST_TEST',
  CB_ANIMATION_TEST = 'CB_ANIMATION_TEST',
  ANIMATION_TEST_CONTAINER = 'ANIMATION_TEST_CONTAINER',
}